
 # <h3 align="center"> <font color='green'>Assignment 02</font></h3> 

Github link:
Chamundeswari Koppisetti: https://github.com/chamundeswarik 

In [1]:
import gym
import tensorflow as tf
import random
import numpy as np

#Load the environment
env = gym.make('FrozenLake-v0')
#Initialize Q-table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])  

In [3]:
#Part A

#Set learning parameters using tensor constants
gamma = tf.constant(0.8, dtype=tf.float32)
alpha = tf.constant(0.1, dtype=tf.float32)
episodes = 10
total = tf.constant(0.0)

#Initialize the temp variables used for the calculation of action
rand = tf.constant(random.uniform(0,1))
epsilon = tf.constant(1, dtype=tf.float32)

#Start the tensorflow session and initialize all the global variables
with tf.Session() as sess:
    tf.global_variables_initializer()
    
    for i in range(episodes):
        print (i)
        # Reset environment and retrieve the first new state
        state = env.reset()
        done = False
        
        # Probability that a uniform random number drawn at each time step has to be smaller for the agent to do exploration
        epsilon = tf.constant(tf.divide(1, (1+i)))
        
        #Start Q-Table Learning
        while not done:
            
            #Choose the action
            rand = tf.constant(random.uniform(0,1))
            def x1(): 
                return tf.constant(env.action_space.sample(), dtype=tf.int32)
            def x2():
                return tf.constant(np.argmax(Q[state]), dtype=tf.int32)
            action = (sess.run(tf.cond(tf.less(epsilon, rand), x1, x2)))
            
            # step(self, action): Step the environment by one timestep. Returns observation, reward, done, info.
            new_state, reward, done, info = env.step(action)
            
            #Update the Q-Table
            a = tf.constant(Q[state, action], dtype=tf.float32)
            b = tf.constant(Q[new_state], dtype=tf.float32)
            r = tf.constant(reward, dtype=tf.float32)
            Q[state, action] += sess.run(tf.multiply(alpha , tf.subtract(tf.add(tf.constant(reward, dtype=tf.float32), tf.multiply(gamma, tf.reduce_max(b))), a)))
            
            #update the state
            state = new_state
            
            total = (tf.add(tf.cast(total, dtype=tf.float32), r))
    
    #Print the Learned Q Table and Average rewards
    print("Average rewards: " + str(sess.run(total)/episodes))
    print("Total Rewards:" + str(sess.run(total)))
    print("Learned Q-Table")
    print(Q)


0
1
2
3
4
5
6
7
8
9
Average rewards: 0.0
Total Rewards:0.0
Learned Q-Table
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


'episodes' should be large enough(>5000), to make Q-table useful and efficient. This program takes some time to run,   hence only considered 10 episodes to run the code. 

This program will give poor performance because it creates several new TensorFlow graph nodes per operation. The underlying assumption in TensorFlow is that we'll build a graph once and then call sess.run() on (various parts of) it multiple times. The first time we run a graph is relatively expensive, because TensorFlow has to build various data structures and optimize the execution of the graph across multiple devices.

We can also define loss function, then use gradient function to optimize the code.

In [4]:
#Part B

from IPython.display import clear_output
import time

episodes = 10
max_steps =1000

#Generating the Episodes
for episode in range(episodes):
    
    #Reset the environment
    state = env.reset()
    step = 0
    done = False
    print(i)
    clear_output()
    print("*****************")
    print("Episodes", episode)
    print("*****************")
    
    for step in range(max_steps):        
        # Take the action that has the best Q value
        action = np.argmax(Q[state])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            print("*****************")
            print("Steps", step)
            print("*****************")
            time.sleep(2)
            break
        state = new_state
        
env.close()

*****************
Episodes 9
*****************
  (Left)
SFFF
FHFH
FFFH
HFFG
*****************
Steps 2
*****************
